### ISSUE TITLE
Incorrect devices are displayed in the Device Type dropdown

### ISSUE THREAD

**Issue by HymaKanchiAU** [aehrc/snomio#449] opened 2023-12-04 00:41 UTC
When searching for the device types in the dropdown products are being displayed as shown below which is incorrect.

![image](https://github.com/aehrc/snomio/assets/126848487/c96ba576-a0f7-499a-b6d4-27a2074fb017)

**Comment by dionmcm** [comment] 2023-12-12 00:58
Binding needs to be addressed to make sure it is correct

**Comment by dionmcm** [comment] 2023-12-14 01:54
OK, so this one is quite tricky.

The problem is that the "right" values to select for device type are from the Biomedical device hierarchy. That is a big hierarchy (about 7,000) and the actual in use values after the AMT v4 transform is only the following 7 which are unlikely to expand, but possible.

ID | Preferred term
---|----
999001041000168101|Diagnostic strip
333453004|Dressing
360041000|Implant
353983009|Medicated dressing
466056002|Patch
1675831000168103|Sponge
76705002|Stick

Not sure if @lawley or @MattCordell have any better suggestions, but my suggestions are

- Set the binding to `^ 929360071000036103.999000061000168105` which will make the user select from one of the existing used values, but allow them to "break out" if they can't find what they want to search and pick from unbranded things from the Biomedical device hierarchy `(< 63653004) minus (* : 774158006 = *)`. Once they "break out" and add a new product with that new value, that new value will appear in `^ 929360071000036103.999000061000168105`.
- Create a reference set, probably managed in RT2, that is used for the binding. Start with these 7 values in it, and tell the authors that if they need to use a new value, they first need to add it to the reference set and have that change promoted first.

I can imagine the first option being a drop down list they can pick from with the 7 values, with a button beside that which pops a modal dialog getting them to search from unbranded things from the Biomedical device hierarchy to add if they want to. When they dismiss the dialog it could populate the value, and once they create the product the drop box for further changes will be automatically expanded.

**Comment by dionmcm** [comment] 2023-12-14 04:10
Actually I think we need a common pattern for this. We want to direct the user to use one of the already in use values for a qualifier rather than picking a new one arbitrarily. This applies to $448 as well, and maybe others,

**Comment by kylynnloi** [comment] 2023-12-18 23:52
this will be resolved by #448

**Closed by kylynnloi** 2023-12-18 23:52 UTC
Labels: bug, MVP, EPIC: Authoring assistance, author
