### ISSUE TITLE
Improve speed of Snowstorm calls

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#252] opened 2023-10-04 02:26 UTC
The following functions are currently encountering big delays when making Snowstorm calls:
* product search (15 second delay after entering three characters)
* 7-box model screen population (up to 3.5min delay when loading Nexium HP7)

Initial testing shows these problems are reduced when using a local instance of Snowstorm, which contains a subset of the SCT-AU dataset.  It is unclear whether the delays are being caused by the reduced amount of data, or by having Snowstorm running locally.

These delays require workarounds to improve the responsiveness of the Snomio screens.

---
### Acceptance Criteria

1. After typing at least three characters of a concept's name into the search field at the top of the authoring screen, the list of matching concepts appears in no more than 3 seconds.
2. After selecting a product from the search field, the 7-box model screen for the product is loaded and displayed in no more than 3 seconds.

**Comment by kylynnloi** [comment] 2023-11-06 00:05
duplicate of #220

**Closed by kylynnloi** 2023-11-06 00:05 UTC
Labels: bug, MVP, EPIC: One tool
